name: CodeEditorDemo
options: 
  bundleIdPrefix: code.editor
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  deploymentTarget:
    macOS: 12.0
packages:
  CodeEditor:
    path: ../
    majorVersion: 1.2.0
targets:
  Demo:
    type: application
    platform: macOS
    sources: Sources
    info:
      path: Sources/Info.plist
    dependencies: 
    - package: CodeEditor